### ISSUE TITLE
IS LIFE WORTH LIVING?

### ISSUE THREAD

**Issue by hsiaoyi0504** [hsiaoyi0504/awesome-cheminformatics#36]
https://iwatobipen.wordpress.com/

**Comment by yamasakih** [comment]
Hi, I think that it is duplicated with this PR?

https://github.com/hsiaoyi0504/awesome-cheminformatics/pull/34

**Comment by iwatobipen** [comment]
Thanks for taking my blogpost!

**Comment by hsiaoyi0504** [comment]
@yamasakih Oops, thanks for reminding me! @iwatobipen 🤓
